version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.3-browsers-legacy
    working_directory: ~/repo
    steps:
    - checkout
    - run: gem update bundler
    - type: cache-restore
      key: bundle-{{ checksum "Gemfile.lock" }}
    - run: bundle install --jobs=8 --retry=3 --path /tmp/bundle
    - type: cache-save
      key: bundle-{{ checksum "Gemfile.lock" }}
      paths:
      - /tmp/bundle
    - run: bundle exec rubocop -a
    - run: git diff --exit-code
    - run: bundle exec rake
    - run: gem build safe_pretty_json.gemspec
    - run: gem install safe_pretty_json-*.gem
    - run: ruby .circleci/test.rb
    - run: ruby bench/bench.rb
  deploy:
    docker:
    - image: circleci/ruby:2.5.3-browsers-legacy
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: deploy
        command: |
          mkdir ~/.gem
          echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
          chmod 0600 /home/circleci/.gem/credentials

          gem build safe_pretty_json.gemspec
          gem push "safe_pretty_json-$(git describe --tags).gem"
workflows:
  version: 2
  test-deploy:
    jobs:
    - build
    - deploy:
        filters:
          tags:
            only: /.*/
          branches:
            ignore: /.*/
